export const data=[
    {
        img:"images/1.jpg",
        quantity:4,
        price:12,
    },
    {
        img:"images/2.jpg",
        quantity:2,
        price:30
    },
    {
        img:"images/3.jpg",
        quantity:1,
        price:90
    },
    {
        img:"images/4.jpg",
        quantity:2,
        price:10
    },
    {
        img:"images/5.jpg",
        quantity:1,
        price:20
    },
    {
        img:"images/p3.jpg",
        quantity:1,
        price:13
    }
    ,{
        img:"images/p4.jpg",
        price:45,
        quantity:3
    }
    ,{
        img:"images/p5.jpg",
        price:34,
        quantity:2,
    },
    {
        img:"images/p6.jpg",
        price:33,
        quantity:1
    }
   
]